USE DadosFeminicidio


-- Feminicidios por ano de 2015 a 2022
SELECT ANO_ESTATISTICA FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2022'
--195
SELECT ANO_ESTATISTICA FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2021'
--140
SELECT ANO_ESTATISTICA FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2020'
--180
SELECT ANO_ESTATISTICA FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2019'
--184
SELECT ANO_ESTATISTICA FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2018'
--136
SELECT ANO_ESTATISTICA FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2017'
--121
SELECT ANO_ESTATISTICA FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2016'
--63
SELECT ANO_ESTATISTICA FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2015'
--41

--Quantidade de Feminicidios em cada Local por ano
SELECT DESC_TIPOLOCAL, ANO_ESTATISTICA, COUNT(ANO_ESTATISTICA) AS 'QNTD CASOS' FROM Feminicidio 
--WHERE ANO_ESTATISTICA = '2015'
GROUP BY DESC_TIPOLOCAL, ANO_ESTATISTICA

SELECT * FROM Feminicidio

--quantidade das vitimas ao ano e sua cor de pele
SELECT COR_PELE, ANO_ESTATISTICA, COUNT(ANO_ESTATISTICA) AS 'QNTD CASOS' FROM Feminicidio 
--WHERE ANO_ESTATISTICA = '2015'
GROUP BY COR_PELE, ANO_ESTATISTICA

--Tipo de profissao de cada vitima e sua cor
SELECT COR_PELE, PROFISSAO, COUNT(PROFISSAO) AS 'QNTD CASOS' FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2022'
GROUP BY COR_PELE,PROFISSAO

SELECT COR_PELE,PROFISSAO, ANO_ESTATISTICA, COUNT(ANO_ESTATISTICA) AS 'QNTD CASOS' FROM Feminicidio 
WHERE ANO_ESTATISTICA = '2015'
GROUP BY COR_PELE,PROFISSAO, ANO_ESTATISTICA

SELECT * FROM Feminicidio

--
SELECT HORA_FATO, DESC_TIPOLOCAL, PROFISSAO,IDADE_PESSOA FROM Feminicidio
WHERE HORA_FATO BETWEEN '01:00:00' AND '12:00:00'
ORDER BY HORA_FATO
-- 384 CASOS
SELECT HORA_FATO, DESC_TIPOLOCAL, PROFISSAO,IDADE_PESSOA FROM Feminicidio
WHERE HORA_FATO BETWEEN '13:00:00' AND '19:00:00'
ORDER BY HORA_FATO
--248
SELECT HORA_FATO, DESC_TIPOLOCAL, PROFISSAO,IDADE_PESSOA FROM Feminicidio
WHERE HORA_FATO BETWEEN '20:00:00' AND '24:00:00'
ORDER BY HORA_FATO
--205




